---
- name: setup maven
  hosts: all
  roles:
    - roles/setup_maven     
  environment:
       MAVEN_HOME: "/data/apache-maven/3.2.5/apache-maven-3.2.5"
       JAVA_HOME: "/data/java/1.8.0_144/jdk1.8.0_144"
       PATH: "{{ ansible_env.MAVEN_HOME }}/bin:{{ ansible_env.JAVA_HOME }}/bin:{{ ansible_env.PATH }}"
