- name: install and run apache web server
  hosts: all

  vars:
    http_port: 8083
    domain: example.com

  tasks:

    - name: install packages
      apt: 
        name: "{{ item }}" 
        update_cache: yes 
        state: latest
      with_items:
        - apache2
        - git

    - name: enabled mod_rewrite
      apache2_module: 
         name: rewrite 
         state: present
      notify:
        - restart apache2

    - name: apache2 listen on port "{{ http_port }}"
      lineinfile: 
         dest: /etc/apache2/ports.conf 
         regexp: '^Listen ' 
         line: 'Listen {{ http_port }}' 
         state: present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port "{{ http_port }}"
      lineinfile: 
         dest: /etc/apache2/sites-available/000-default.conf
         regexp: '^<VirtualHost \*:' 
         line: '<VirtualHost *:{{ http_port }}>'
      notify:
        - restart apache2

    - name: create virtual host file
      template: 
         src: virtualhost.conf 
         dest: "/etc/apache2/sites-available/{{ domain }}.conf"

    - name: a2ensite "{{ domain }}"
      command: a2ensite "{{ domain }}"
      args:
        creates: "/etc/apache2/sites-enabled/{{ domain }}.conf"
      notify:
        - restart apache2

    - name: clone basic html template
      git: 
        repo: https://github.com/do-community/ansible-apache-tutorial.git 
        dest: /var/www/example.com 
        update: no
    
    - name: delete existing index.html
      file:
        path: /var/www/html/index.html
        state: absent      

    - name: copy index.html to /var/www/html/index.html
      file:
        src: /var/www/example.com/index.html
        dest: /var/www/html/index.html
        mode: 0644
        state: link
      notify:
        - restart apache2     
                
  handlers:
    - name: restart apache2
      service: 
        name: apache2 
        state: restarted
  become: true
  become_user: root

