---
- name: create a disk
  gcp_compute_disk:
      name: "{{ instance_name }}-disk-instance"
      size_gb: "{{ disk_size }}"
      source_image: "{{ source_image }}"
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - "{{ scopes }}"
      state: present
  register: disk

- name: create a network
  gcp_compute_network:
      name: "{{ network_name }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - "{{ scopes }}"
      state: present
  register: network

- name: create a address
  gcp_compute_address:
      name: "{{ instance_name }}-address-instance"
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - "{{ scopes }}"
      state: present
  register: address

- name: create a instance
  gcp_compute_instance:
      state: present
      name: "{{ instance_name }}"
      machine_type: "{{ machine_type }}"
      disks:
        - auto_delete: true
          boot: true
          source: "{{ disk }}"
      network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: 'External NAT'
                nat_ip: "{{ address }}"
                type: 'ONE_TO_ONE_NAT'
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - "{{ scopes }}"
  register: instance

- name: Wait for SSH to come up
  wait_for: 
      host: "{{ address.address }}" 
      port: 22 
      delay: 10 
      timeout: 60

