- name: Create maven directory
  file:
    path: "{{ maven_installation_directory }}/{{ maven_version }}"
    state: directory
    recurse: yes


- name: Create m2 home directory
  file:
    path: "/home/{{ user_name }}/.m2"
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ group_name }}"    
    mode: '0755'
