nexus_version: "3.13.0-01"
nexus_installation_directory: "/data/nexus"
#nexus_download_url: "https://sonatype-download.global.ssl.fastly.net/repository/repositoryManager/3/nexus-{{ nexus_version }}-unix.tar.gz"
nexus_download_url: "http://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}-unix.tar.gz"
nexus_port: 8082
user_name: "ayushbisaria"
group_name: "ayushbisaria"

