---
- name: include all tasks    
  block:
    - include_tasks: "createDirectory.yml"
    - include_tasks: "downloadNexusPackage.yml"
    - include_tasks: "untarNexusPackage.yml"  
    - include_tasks: "changeOwnership.yml"
    - include_tasks: "injectconfiguration.yml"
    - include_tasks: "removeNexusPackage.yml"
  become: true
  become_user: root

- name: start nexus  
  include_tasks: "startNexus.yml"
  
