---
- name: inject nexus properties file user's home
  template:
     src: nexus_properties.j2
     dest: "{{ nexus_installation_directory }}/{{ nexus_version }}/nexus-{{ nexus_version }}/etc/nexus-default.properties"
  
- name: inject nexus properties file user's home
  template:
     src: nexus.rc.j2
     dest: "{{ nexus_installation_directory }}/{{ nexus_version }}/nexus-{{ nexus_version }}/bin/nexus.rc"

